version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_0108AZPPProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: karthik-v2k
  gitBranch: main
services:
- serviceName: project.siqa_git_0108azpp.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GIT_0108AZPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_git_0108azpp.integrations:Call_TPP
  packages:
  - name: SIQA_GIT_0108AZPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_git_0108azpp.integrations:Call_refData
  packages:
  - name: SIQA_GIT_0108AZPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_git_0108azpp.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_0108AZPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_git_0108azpp.referencedata:refData
  packages:
  - name: SIQA_GIT_0108AZPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
